version: '3.8'

services:
  db:
    image: postgres:16
    container_name: todo_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Xgett213
      POSTGRES_DB: todo_db
    volumes:
      - todo_pgdata:/var/lib/postgresql/data

volumes:
  todo_pgdata:
